"""update users

Revision ID: 895128ce1298
Revises: 7bc6083e8668
Create Date: 2026-04-01 22:00:41.555501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895128ce1298'
down_revision = '7bc6083e8668'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('max_questions', sa.Integer(), default=5))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_questions')
    # ### end Alembic commands ###
